[package]
name = "blstrs-pvss-simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blstrs = "0.7.1"
group = "0.13.0"
pairing = "0.23.0"
rand = "0.8.5"
rand_core = "0.6.0"
